name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # main分支，你也可以改成其他分支
      - main
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: | # 执行命令（运行到服务器）cd：要确保服务器有这个目录； wget：下载上一步的release到服务器； tar：解压； 安装依赖；启动服务
            git config --global --unset http.proxy
            git config --global --unset https.proxy
            cd /usr/local/blog/temp/
            rm -rf ai4
            git clone git@github.com:jerryzhaozs/ai4.git
            cd /usr/local/blog/temp/ai4/
            cp -rf docs /usr/local/blog/ai4/
            cp -rf deploy.sh /usr/local/blog/ai4/
            cp -rf package.json /usr/local/blog/ai4/
            cd /usr/local/blog/ai4/
            bash deploy.sh
