# main.yml
name: deploy main
on:
  push:
    branches:
      - master
jobs:
  build:
    # runs-on: centos-latest
    steps:
      - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.1.6
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        ARGS: "-rltgoDzvO"
        SOURCE: './' #仓库根路径
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        TARGET: '/usr/local/blog/'  #目标服务器的路径
        EXCLUDE: "/dist/, /node_modules/"   #排除文件夹
